### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by jayomayan** [lqueryvg/sftp-lambda#15]
Newbie on Serverless here. Is there like an installation guide on this?
This is actually what I have been looking for, for a long time.

**Comment by lqueryvg** [comment]
Hi @jayomayan,

Thanks for your interest.
Regarding an "installation guide"...
In its current form, this repo is more of a library than a product, and as such it's not something which can be "installed". As I said in the README...

> - Deployment of the Lambdas and the related resources (e.g. SQS queues) is up to you.

There are multiple ways to deploy Lambdas - Serverless Framework is just one, and I happen to be a fan.

In the future I'm thinking about either publishing this as an npm/yarn package or (going the other way) publishing as an AWS Serverless Application.

In the meantime, I'll consider writing a short tutorial on how you might set this up with Serverless.

**Comment by jayomayan** [comment]
@lqueryvg I'm totally new to Serverless. If you can guide me a little, that would be a great help for me.
