### ISSUE TITLE
Request for Open Source licensing information

### ISSUE THREAD

**Issue by ooloncoluphid** [lqueryvg/sftp-lambda#25]
Finding your project very helpful, it would be very good to know if, and under which licensing conditions one could make use of it e.g. in a commercial project.
It might be most helpful if you would add an according LICENSE file to your repo.

**Comment by yegortimoshenko** [comment]
Nominally, license is specified here: https://github.com/lqueryvg/sftp-lambda/blob/14a3eefb1f2c00afc6258e0e4a47e5e5ba8a308e/package.json#L16

However, it would really help avoid ambiguity if it was included verbatim in the repo itself. @lqueryvg

**Comment by ooloncoluphid** [comment]
Thank you so much @lqueryvg  ;)
