### ISSUE TITLE
AWS Serverless Application?

### ISSUE THREAD

**Issue by lukateras** [lqueryvg/sftp-lambda#32]
I want to work on a pull request that packages sftp-lambda into an AWS Serverless Application along with relevant documentation. Is this something you'd be interested in merging, @lqueryvg?

**Comment by lqueryvg** [comment]
@yegortimoshenko , yes I'm interested !

**Comment by lqueryvg** [comment]
I just want to add some thoughts and a bit of history.

I have toyed with the idea of making this into an NPM package (in line with #16).
But I'm still on the fence about this.

The idea would be that the javascript code becomes a library and the deployment mechanism is separate.

FYI, I'm using sftp-lambda in a real-life product for one of my clients, but this is deployed as a Serverless stack, and the code is basically copy pasted into another repo. I would still therefore like sftp-lambda to be compatible with Serverless stacks, with an AWS Application being an optional way to deploy it. I.e. try to keep the AWS Application specifics separate to the core functionality as much as possible.

Please can you bear this in mind.
I'm open to discussion and I'm keen to see what you come up with.

**Comment by yegortimoshenko** [comment]
Got you and I believe that retaining platform agnosticism is possible! I think adding AWS Lambda Application code should be mostly limited to two new files: `index.js` and `template.yaml`. Making this into both an AWS Lambda Application and an NPM package should also be possible!

I'll keep everything you've said in mind while working on the PR :)
