### ISSUE TITLE
Printing file contents is not practical for large files

### ISSUE THREAD

**Issue by lukateras** [lqueryvg/sftp-lambda#37]
Sorry if I'm overwhelming you with tickets/feedback and let me know if I should space it all out a bit!

I have a question about this line:

https://github.com/lqueryvg/sftp-lambda/blob/1a6dede30c5cc6b4ce5a64005eaf6a92734fef94/handlers/lib/pullTree.js#L46

Unfortunately, this is not practical for large files :( Would you consider a patch that removes the line? If not, what could be an acceptable alternative?

**Comment by lqueryvg** [comment]
@yegortimoshenko, I agree. It's overkill.
A nice alternative might be to print the size in bytes instead.
